name: GT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - regex=2019.04.14
  - numpy
  - pandas
  - tqdm
  - pyyaml
  - yaml
  - pathos
  - tensorboard
  - pip:
    - torch==1.1
    - spacy-nightly
