name: GT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - regex=2019.04.14
  - numpy
  - pandas
  - tqdm
  - pyyaml
  - yaml
  - pathos
  - pytorch=1.1.0
  - tensorflow
  - tensorboard
  - tensorboardX
  - pip:
    - pytorch-transformers
    - fairseq
    - spacy-nightly
