name: GT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - regex
  - numpy
  - pandas
  - tqdm
  - pyyaml
  - yaml
  - pathos
  - tensorboard
  - pip:
    - torch==1.3
    - spacy-nightly
